### Employee Workforce Exploratory Data Analysis

#### Business Problem

Organizations collect employee data to understand workforce performance, salary distribution, employee satisfaction, and workforce trends.

The objective of this project is to analyze employee data, identify data quality issues, clean the dataset, explore important relationships, and generate meaningful business insights that can support better decision-making.



#### Project Objectives

- Understand the dataset structure.
- Identify data quality issues.
- Handle missing values.
- Remove duplicate records.
- Clean inconsistent data.
- Detect outliers.
- Perform univariate analysis.
- Perform bivariate analysis.
- Perform multivariate analysis.
- Generate business insights and recommendations.

In [1]:
#import libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
# Import warnings library
import warnings

# Ignore unnecessary warnings
warnings.filterwarnings("ignore")

In [4]:
#load dataset
df = pd.read_csv("../data/raw/employee_data.csv")

In [5]:
#display first five rows of dataset
df.head()

,Employee_ID,Name,Gender,Age,Department,City,Experience_Years,Education_Level,Job_Level,Salary,Performance_Score,Joining_Date,Is_Remote,Employment_Type,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score,Attrition,Email
0,1001,Farhan Ahmed,Male,38,Marketing,Karachi,4,Intermediate,Senior,111512,7.9,2014-09-18,True,Full-time,169,150,77,1.1,No,farhan.ahmed1001@company.com
1,1002,Farhan Chaudhry,Female,35,Design,Rawalpindi,8,Intermediate,Senior,NaN,6.7,2017-06-27,True,Part-time,183,7,11,2.5,No,farhan.chaudhry1002@company.com
2,1003,Hira Sheikh,Female,23,Design,Lhore,3,MPhil,Junior,56050,NaN,2015-07-24,True,Full-time,177,6,29,4.5,No,hira.sheikh1003@company.com
3,1004,Saad Butt,Female,NaN,Support,Islamabad,6,Master,Senior,118533,NaN,2017-11-02,True,Full-time,188,18,71,1.9,No,NaN
4,1005,Shahzaib Qureshi,Male,35,IT,Peshawar,10,MPhil,Junior,77905,9.3,2021-01-21,True,Full-time,190,30,18,NaN,No,shahzaib.qureshi1005@company.com

In [6]:
#display last five rows of dataset
df.tail()

,Employee_ID,Name,Gender,Age,Department,City,Experience_Years,Education_Level,Job_Level,Salary,Performance_Score,Joining_Date,Is_Remote,Employment_Type,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score,Attrition,Email
515,1095,Hassan Aslam,Male,29,Operations,Rawalpindi,1,Intermediate,Mid,69817,5.8,2019-01-22,Yes,Contract,206,19,10,2.0,No,hassan.aslam1095@company.com
516,1418,Hira Aslam,Male,47,HR,Lahore,11,Master,Junior,64101,6.8,2022-05-26,False,Full-time,143,10,18,4.1,No,hira.aslam1418@company.com
517,1442,Fatima Raza,Female,49,Marketing,Multan,18,Master,Junior,77004,6.0,2017-11-27,Yes,Contract,162,22,70,2.0,No,fatima.raza1442@company.com
518,1091,Farhan Malik,Female,45,IT,Rawalpindi,4,MPhil,Manager,206791,8.7,2017-02-01,False,Full-time,223,18,31,4.8,Yes,farhan.malik1091@company.com
519,1097,Bilal Butt,Male,57,it,Rawalpindi,20,Intermediate,Mid,141557,6.4,2020-10-10,False,Full-time,227,26,38,2.8,No,bilal.butt1097@company.com

In [7]:
#display dataset shape
df.shape

(520, 20)

In [8]:
#dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         520 non-null    int64
 1   Name                520 non-null    object
 2   Gender              520 non-null    object
 3   Age                 485 non-null    object
 4   Department          520 non-null    object
 5   City                491 non-null    object
 6   Experience_Years    520 non-null    int64
 7   Education_Level     520 non-null    object
 8   Job_Level           520 non-null    object
 9   Salary              494 non-null    object
 10  Performance_Score   499 non-null    float64
 11  Joining_Date        520 non-null    object
 12  Is_Remote           520 non-null    object
 13  Employment_Type     520 non-null    object
 14  Monthly_Work_Hours  520 non-null    int64
 15  Projects_Completed  520 non-null    int64
 16  Training_Hours      520 non-null    int64
 17  Satisfaction_Score  502 non-null    float64
 18  Attrition           520 non-null    object
 19  Email               503 non-null    object
dtypes: float64(2), int64(5), object(13)
memory usage: 81.4+ KB

In [9]:
#display column names
df.columns

Index(['Employee_ID', 'Name', 'Gender', 'Age', 'Department', 'City',
       'Experience_Years', 'Education_Level', 'Job_Level', 'Salary',
       'Performance_Score', 'Joining_Date', 'Is_Remote', 'Employment_Type',
       'Monthly_Work_Hours', 'Projects_Completed', 'Training_Hours',
       'Satisfaction_Score', 'Attrition', 'Email'],
      dtype='object')

In [10]:
#datatypes of columns
df.dtypes

Employee_ID             int64
Name                   object
Gender                 object
Age                    object
Department             object
City                   object
Experience_Years        int64
Education_Level        object
Job_Level              object
Salary                 object
Performance_Score     float64
Joining_Date           object
Is_Remote              object
Employment_Type        object
Monthly_Work_Hours      int64
Projects_Completed      int64
Training_Hours          int64
Satisfaction_Score    float64
Attrition              object
Email                  object
dtype: object

In [11]:
#display statistical summary of numerical columns
df.describe()

,Employee_ID,Experience_Years,Performance_Score,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score
count,520.000000,520.000000,499.000000,520.000000,520.000000,520.000000,502.000000
mean,1249.225000,10.519231,7.443687,184.725000,19.759615,40.278846,3.020518
std,144.110872,7.034433,1.483610,25.634893,22.040554,23.873001,1.167130
min,1001.000000,0.000000,5.000000,140.000000,1.000000,0.000000,1.000000
25%,1122.750000,4.000000,6.100000,162.750000,9.000000,19.000000,2.000000
50%,1246.500000,10.000000,7.400000,185.500000,19.000000,40.000000,3.100000
75%,1374.000000,16.000000,8.700000,206.250000,28.000000,62.000000,4.000000
max,1500.000000,25.000000,9.900000,230.000000,300.000000,80.000000,5.000000

#### Initial Observation

After loading the dataset:

- Successfully loaded the employee dataset.
- Verified the dataset dimensions.
- Reviewed column names and data types.
- Generated statistical summary.
- Ready for detailed data quality assessment.